name: apply

on:
  workflow_dispatch:
# OIDC permissions for keyless authentication
permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  common:
    # Reuse the compile workflow (can even point to another repo, see the docs)
    uses: ./.github/workflows/common.yaml
  terraform-apply:
    name: apply-check
    needs: common
    runs-on: ubuntu-24.04-arm
    environment: ${{ needs.common.outputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Terraform
        id: setup-terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3
      - name: Configure AWS credentials via OIDC
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.aws_iam_role }}
          role-session-name: GitHub-Role-${{ github.run_id }}
          aws-region: ${{ vars.aws_region }}
      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-artifact-${{ github.sha }}
          path: terraform # Download to current directory
          run-id: ${{ github.run_id }}
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
      - name: After path
        # working-directory: terraform
        run: |
          echo "$(pwd)"
          echo "$(ls -al)"
          echo "$(ls -al terraform)"
          echo "The value of TF_WORKSPACE is ${{ needs.common.outputs.tf_workspace }}"
          echo "The value of ARTIFACT_NAME is ${{ needs.common.outputs.artifact_name }}"
      - name: Terraform Init
        run: terraform init
        working-directory: terraform
      - name: Terraform Show Workspace
        working-directory: terraform
        run: |
          terraform workspace select ${{ needs.common.outputs.tf_workspace }}
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply --auto-approve