name: feature-branch-destroy
on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [develop]
  pull_request_review:
    types: [submitted]



permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  common:
    name: common-destory-check
    # Reuse the compile workflow (can even point to another repo, see the docs)
    uses: ./.github/workflows/destroy.yaml
    with:
      destroy: "true"