name: feature-branch-destroy
on:
  pull_request:
    types: [closed]
    branches: [develop]



permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  check_condition_and_call:
    runs-on: ubuntu-latest
    outputs:
      destroy: ${{ steps.set_output.outputs.destroy }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Perform a check
        id: set_output
        run: |
          DESTROY=true
          echo "destroy=$DESTROY" >> $GITHUB_OUTPUT
      - name: Logging files
        run: |
          echo $(ls -al)
      - name: Call the reusable workflow
        # The 'if' condition is crucial for controlling the next workflow run
        if: ${{ fromJSON(steps.set_output.outputs.destroy) == true }}
        uses: ./.github/workflows/destroy.yml # Path to your reusable workflow
        with:
          # Pass the boolean output from the previous step
          destroy: ${{ steps.set_output.outputs.destroy }}