name: feature-branch-destroy
on:
  pull_request:
    types: [closed]
    branches: [develop]



permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  common:
    name: common-destory-check
    if: startsWith(github.event.pull_request.head.ref, 'feature/')
    # Reuse the compile workflow (can even point to another repo, see the docs)
    uses: ./.github/workflows/destroy.yaml
    with:
      destroy: true